### PR TITLE
Created command menu entries on the Default.sublime-commands with:

### PR DESCRIPTION
**Pull request by evandrocoan**
Indent and braces: Automatically embrace selection
Indent and braces: Embrace with brackes
Indent and braces: Force from new line

from the main page at:
https://github.com/Epskampie/sublime_indent_and_braces

### CODE REVIEW

**Comment by Epskampie** [comment]
Haha, I like the "embrace" :-)

But you forgot a t in the word "brackes", could you fix that?

**Comment by evandrocoan** [comment]
Yeah. I just fixed.

**Comment by Epskampie** [comment]
Cool, merged, thanks for contributing!

**Comment by evandrocoan** [comment]
You are welcome 👍

**Pull request merged**
